# Generated by Django 4.2.16 on 2026-01-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allianceauth_oidc", "0004_allianceauthapplication_allowed_origins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                max_length=44,
            ),
        ),
    ]
