# Generated by Django 5.2.12 on 2026-06-02 01:03

import oauth2_provider.generators
import oauth2_provider.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "allianceauth_oidc",
            "0005_alter_allianceauthapplication_authorization_grant_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="client_secret",
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text="Client secret for authentication",
                max_length=255,
            ),
        ),
    ]
