# Generated by Django 5.2.12 on 2026-07-27 01:22

import oauth2_provider.generators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allianceauth_oidc", "0006_alter_allianceauthapplication_client_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="allianceauthapplication",
            name="cimd_expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the cached Client ID Metadata Document should be re-fetched",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allianceauthapplication",
            name="registration_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("dcr", "Dynamic Client Registration"),
                    ("cimd", "Client ID Metadata Document"),
                ],
                default="manual",
                help_text="How this application was registered (manual, DCR per RFC 7591, or CIMD)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="client_id",
            field=models.CharField(
                db_index=True,
                default=oauth2_provider.generators.generate_client_id,
                max_length=255,
                unique=True,
            ),
        ),
    ]
